// Hand-written to match contracts/src/AgentVault.sol exactly (verified against
// the Solidity source, not generated from a build artifact — apps/agent must
// be runnable without a `forge build` step). Only the surface the runtime and
// web app actually touch; internal helpers (_valueOf, _nav, etc.) are omitted.
export const agentVaultAbi = [
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "quoteToken",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "agent",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "agentExpiry",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "paused",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "bool" }],
  },

  {
    type: "function",
    name: "maxNotionalPerTrade",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "maxDailyNotional",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "maxPositionBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "minSecondsBetweenTrades",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "maxSlippageBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "lastTradeTimestamp",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "BPS_DENOMINATOR",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "MAX_STALENESS_LIMIT",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "NOTIONAL_WINDOW",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },

  {
    type: "function",
    name: "allowedRoutersLength",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "allowedRouters",
    stateMutability: "view",
    inputs: [{ type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "allowedTokensLength",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "allowedTokens",
    stateMutability: "view",
    inputs: [{ type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "isTokenAllowed",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "isRouterAllowed",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "tokenDecimals",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "uint8" }],
  },
  {
    type: "function",
    name: "priceFeeds",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [
      { type: "address", name: "aggregator" },
      { type: "uint8", name: "priceDecimals" },
      { type: "uint32", name: "maxStaleness" },
    ],
  },

  {
    type: "function",
    name: "nav",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },

  {
    type: "function",
    name: "feeRecipient",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "feeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "highWaterMark",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },

  {
    type: "function",
    name: "setPriceFeed",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address", name: "token" },
      { type: "address", name: "aggregator" },
      { type: "uint32", name: "maxStaleness" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setPolicy",
    stateMutability: "nonpayable",
    inputs: [
      {
        type: "tuple",
        name: "policy",
        components: [
          { type: "address[]", name: "allowedRouters" },
          { type: "address[]", name: "allowedTokens" },
          { type: "uint256", name: "maxNotionalPerTrade" },
          { type: "uint256", name: "maxDailyNotional" },
          { type: "uint256", name: "maxPositionBps" },
          { type: "uint256", name: "minSecondsBetweenTrades" },
          { type: "uint256", name: "maxSlippageBps" },
        ],
      },
    ],
    outputs: [],
  },

  {
    type: "function",
    name: "deposit",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address", name: "token" },
      { type: "uint256", name: "amount" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address", name: "token" },
      { type: "uint256", name: "amount" },
      { type: "address", name: "to" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "executeTrade",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address", name: "tokenIn" },
      { type: "address", name: "tokenOut" },
      { type: "uint256", name: "amountIn" },
      { type: "uint256", name: "minOut" },
      { type: "address", name: "router" },
      { type: "bytes", name: "swapCalldata" },
    ],
    outputs: [{ type: "uint256", name: "amountOut" }],
  },
  {
    type: "function",
    name: "setAgent",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address", name: "newAgent" },
      { type: "uint256", name: "expiry" },
    ],
    outputs: [],
  },
  { type: "function", name: "revokeAgent", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "pause", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "unpause", stateMutability: "nonpayable", inputs: [], outputs: [] },
  {
    type: "function",
    name: "collectFee",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },

  {
    type: "event",
    name: "TradeExecuted",
    inputs: [
      { type: "address", name: "tokenIn", indexed: true },
      { type: "address", name: "tokenOut", indexed: true },
      { type: "uint256", name: "amountIn", indexed: false },
      { type: "uint256", name: "amountOut", indexed: false },
      { type: "address", name: "router", indexed: false },
      { type: "uint256", name: "notionalUsd", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Deposited",
    inputs: [
      { type: "address", name: "from", indexed: true },
      { type: "address", name: "token", indexed: true },
      { type: "uint256", name: "amount", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Withdrawn",
    inputs: [
      { type: "address", name: "token", indexed: true },
      { type: "uint256", name: "amount", indexed: false },
      { type: "address", name: "to", indexed: true },
    ],
  },
  { type: "event", name: "VaultPaused", inputs: [] },
  { type: "event", name: "VaultUnpaused", inputs: [] },
  { type: "event", name: "PolicyUpdated", inputs: [] },
] as const;
